spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://monorail.proxy.rlwy.net:25265/railway
    username: root
    password: eGBf1C3BA6fbG34hE523-4GB-gec-15D
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: true
    mail:
      host: smtp.gmail.com
      port: 587
      username: empresa.comvol@gmail.com
      password: fvqnrchwgxaqfbcp
